In [1]:
!pip install openpyxl plotly

Requirement already satisfied: openpyxl in c:\users\nagashree k s\anaconda3\lib\site-packages (3.0.9)
Requirement already satisfied: plotly in c:\users\nagashree k s\anaconda3\lib\site-packages (6.9.0)
Requirement already satisfied: et-xmlfile in c:\users\nagashree k s\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\nagashree k s\anaconda3\lib\site-packages (from plotly) (2.21.0)
Requirement already satisfied: packaging in c:\users\nagashree k s\anaconda3\lib\site-packages (from plotly) (21.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\nagashree k s\anaconda3\lib\site-packages (from packaging->plotly) (3.0.4)

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

from IPython.display import display,HTML

pio.renderers.default = "notebook_connected"

pd.set_option("display.max_columns",None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [3]:
display(HTML("""

<style>

body{

background:#F7F2E8;

}

.jp-Notebook{

background:#F7F2E8 !important;

}

.output{

background:#F7F2E8;

}

.dashboard-title{

background:#F7F2E8;

padding:25px;

border-radius:18px;

box-shadow:0px 2px 10px rgba(0,0,0,.15);

margin-bottom:20px;

}

.card{

background:white;

padding:20px;

border-radius:18px;

box-shadow:0px 4px 12px rgba(0,0,0,.15);

text-align:center;

width:220px;

}

</style>

"""))

In [4]:
display(HTML("""

<div class="dashboard-title">

<h1 style="text-align:center;
font-size:46px;
color:#3E2723;">

🌍 Global Military Firepower Dashboard

</h1>

<h3 style="text-align:center;
color:#795548;">

Military Analytics & Comparison Dashboard

</h3>

</div>

"""))

In [5]:
df = pd.read_excel(
    "military_final.xlsx",
    sheet_name="Wide_Format"
)

print("Dataset Loaded Successfully")

print("Rows :",df.shape[0])

print("Columns :",df.shape[1])

df.head()

Dataset Loaded Successfully
Rows : 145
Columns : 67

,country,power_index,total_population,total_military_manpower,fit_for_service,population_reaching_military_age_annually,active_personnel,reserve_personnel,paramilitary,total_military_aircraft,fighter_aircraft,attack_aircraft,transport_aircraft,trainer_aircraft,special_mission_aircraft,tanker_aircraft,total_military_helicopters,attack_helicopters,tanks,armored_fighting_vehicles,self_propelled_artillery,towed_artillery,rocket_projectors,total_naval_fleet,total_naval_fleet_tonnage_mt,aircraft_carriers,helicopter_carriers,submarines,destroyers,frigates,corvettes,coastal_patrol_craft,mine_warfare_craft,defense_budget_usd,external_debt_usd,purchasing_power_parity_usd,foreign_exchange_and_gold_reserves_usd,total_serviceable_airports,labour_force,major_ports_and_terminals,total_merchant_marine_fleet,railway_coverage_km,roadway_coverage_km,oil_production_bbl,oil_consumption_bbl,proven_oil_reserves_bbl,natural_gas_production_cum,natural_gas_consumption_cum,proven_natural_gas_reserves_cum,coal_production_cum,coal_consumption_mt,proven_coal_reserves_cum,total_land_area_sq_km,coastline_coverage_km,border_coverage_km,waterway_coverage_km,continent,region,gdp,alliance,power_index_rank,total_assets,gdp_rank,power_index_rank_gap,assets_per_capita,budget_to_gdp_ratio,nato_flag
0,Afghanistan,2.7342,40121552,15647405,8826741,842553,75000,0,90000,5,0,0,2,0,0,0,3,0,0,3902,0,0,0,0,10190,0,0,0,0,0,0,0,0,145000000,1929750000,82238000000,8852092000,68,9133000,0,0,0 km,34903 km,0 bbl,58000 bbl,0 bbl,80200000 Cu.M,80200000 Cu.M,49554000000 Cu.M,767000 Cu.M,503000 mt,66000000 Cu.M,652230 km,0 km,5987 km,1200 km,Asia,Southern Asia,9.202187e+10,NATO,121,3907,60,-61,0.000097,0.001576,1
1,Albania,1.7258,3107100,1522479,1292554,62142,7500,0,500,20,0,0,1,0,0,0,19,0,0,1492,10,0,270,33,10190,0,0,0,0,0,0,33,0,720037190,5363000000,51360000000,6516000000,3,1370000,3,69,424 km,3581 km,14000 bbl,21000 bbl,150000000 bbl,50623000 Cu.M,50623000 Cu.M,5692000000 Cu.M,473000 Cu.M,255000 mt,522000000 Cu.M,28748 km,362 km,691 km,41 km,Europe,Southern Europe,1.888210e+10,NATO,77,1825,127,50,0.000587,0.038133,1
2,Algeria,0.4849,47022473,22570787,19185169,752360,130000,150000,150000,620,111,42,63,90,10,4,300,74,1485,24920,224,483,188,111,83480,0,0,6,0,8,8,75,3,25000000000,4764000000,722912000000,83007000000,95,13294000,17,119,4020 km,112696 km,1443000 bbl,446000 bbl,12200000000 bbl,100726000000 Cu.M,47963000000 Cu.M,4504000000000 Cu.M,0 Cu.M,3000 mt,233000000 Cu.M,2381740 km,998 km,6734 km,0 km,Africa,Northern Africa,1.920000e+11,NATO,27,28031,48,21,0.000596,0.130208,1
3,Angola,1.1045,37202061,7440412,3720206,372021,107000,0,10000,278,67,6,32,56,2,0,115,14,319,2258,25,575,116,32,10190,0,0,0,0,0,0,32,0,31200000000,45299000000,278239000000,14243000000,107,15961000,21,64,2761 km,76000 km,1175000 bbl,121000 bbl,7783000000 bbl,5514000000 Cu.M,1397000000 Cu.M,343002000000 Cu.M,0 Cu.M,0 mt,0 Cu.M,1246700 km,1600 km,5369 km,1300 km,Africa,Sub-Saharan Africa,1.070000e+11,NATO,59,3603,58,-1,0.000097,0.291589,1
4,Argentina,0.5983,46994384,20677529,17575900,704916,108000,12370,20000,241,23,11,25,71,13,2,96,0,362,22432,20,172,27,42,122128,0,0,2,3,0,6,13,0,993919790,74362000000,1213000000000,29560000000,764,22286000,37,201,17866 km,240000 km,807000 bbl,749000 bbl,2483000000 bbl,43280000000 Cu.M,46228000000 Cu.M,396464000000 Cu.M,869000 Cu.M,2534000 mt,799999000 Cu.M,2780400 km,4989 km,11968 km,11000 km,Americas,Latin America and the Caribbean,6.330000e+11,NATO,32,23296,19,-13,0.000496,0.001570,1

In [7]:
countries = len(df)
aircraft = int(df["total_military_aircraft"].sum())
budget = df["defense_budget_usd"].sum() / 1e9
power = round(df["power_index"].mean(), 4)

display(HTML(f"""

<div style="display:flex;
gap:25px;
justify-content:center;
margin-top:20px;">

<div class="card"
title="Total number of countries available in the dataset">

<h3>🌍 Countries</h3>

<h1>{countries}</h1>

</div>

<div class="card"
title="Total military aircraft across all countries">

<h3>✈ Aircraft</h3>

<h1>{aircraft:,}</h1>

</div>

<div class="card"
title="Combined defense budget of all countries (in Billion USD)">

<h3>💰 Budget</h3>

<h1>{budget:.2f} B</h1>

</div>

<div class="card"
title="Average Global Firepower Index (lower is stronger)">

<h3>⚔ Avg Power</h3>

<h1>{power}</h1>

</div>

</div>

"""))

In [9]:
import plotly.io as pio
pio.renderers.default = "notebook"

In [12]:
import plotly.express as px

top10 = df.sort_values(
    by="power_index",
    ascending=True
).head(10)

fig = px.bar(
    top10,
    x="country",
    y="power_index",
    color="power_index",          # Automatic gradient
    text="power_index",
    color_continuous_scale="Brwnyl",   # Brown → Yellow gradient
    title="🏆 Top 10 Countries by Power Index"
)

fig.update_traces(
    texttemplate="%{text:.3f}",
    textposition="outside",
    hovertemplate="<b>%{x}</b><br>Power Index: %{y:.3f}<extra></extra>"
)

fig.update_layout(
    paper_bgcolor="#F7F2E8",
    plot_bgcolor="white",
    height=550,
    title_x=0.5,
    xaxis_title="Country",
    yaxis_title="Power Index",
    coloraxis_showscale=False
)

fig.show()

In [13]:
top_budget = df.sort_values(
    by="defense_budget_usd",
    ascending=False
).head(10)

fig = px.bar(
    top_budget,
    x="country",
    y="defense_budget_usd",
    color="defense_budget_usd",
    text="defense_budget_usd",
    color_continuous_scale="YlOrBr",
    title="💰 Top 10 Defense Budgets"
)

fig.update_traces(
    texttemplate="%{text:.2s}",
    textposition="outside",
    hovertemplate="<b>%{x}</b><br>Defense Budget: $%{y:,.0f}<extra></extra>"
)

fig.update_layout(
    paper_bgcolor="#F7F2E8",
    plot_bgcolor="white",
    title_x=0.5,
    title_font_size=22,
    height=550,
    xaxis_title="Country",
    yaxis_title="Defense Budget (USD)",
    coloraxis_showscale=False
)

fig.show()

In [23]:
continent_assets = (
    df.groupby("continent")["total_assets"]
      .sum()
      .reset_index()
      .sort_values("total_assets", ascending=False)
)


colors = [
    "#0B1F3A",  # Navy Blue
    "#1F4E79",  # Dark Blue
    "#2E75B6",  # Steel Blue
    "#5B9BD5",  # Medium Blue
    "#9DC3E6",  # Light Blue
    "#D9EAF7",  # Pale Blue
    "#F4F8FC"   # Very Light Blue
]
fig = px.pie(
    continent_assets,
    names="continent",
    values="total_assets",
    hole=0.55,
    title="🌍 Military Assets by Continent",
    color_discrete_sequence=colors
)

fig.update_traces(
    textposition="inside",
    textinfo="percent+label",
    hovertemplate="<b>%{label}</b><br>Total Assets: %{value:,}<br>%{percent}<extra></extra>",
    marker=dict(line=dict(color="white", width=2))
)

fig.update_layout(
    paper_bgcolor="#F7F2E8",
    plot_bgcolor="#F7F2E8",
    title_x=0.5,
    title_font_size=22,
    height=600,
    legend_title="Continent"
)

fig.show()

In [24]:
fig = px.scatter(
    df,
    x="total_military_aircraft",
    y="tanks",
    size="defense_budget_usd",
    color="continent",
    hover_name="country",
    title="✈ Aircraft vs Tanks by Country",
    color_discrete_sequence=px.colors.qualitative.Bold
)

fig.update_layout(
    paper_bgcolor="#F7F2E8",
    plot_bgcolor="white",
    title_x=0.5,
    title_font_size=22,
    height=600,
    xaxis_title="Total Military Aircraft",
    yaxis_title="Number of Tanks"
)

fig.update_traces(
    marker=dict(
        line=dict(width=1, color="white")
    )
)

fig.show()

In [25]:
region_data = (
    df.groupby("region")["active_personnel"]
      .sum()
      .reset_index()
      .sort_values("active_personnel", ascending=False)
)

fig = px.bar(
    region_data,
    x="region",
    y="active_personnel",
    color="active_personnel",
    text="active_personnel",
    color_continuous_scale="YlOrBr",
    title="👥 Active Personnel by Region"
)

fig.update_traces(
    texttemplate="%{text:.2s}",
    textposition="outside",
    hovertemplate="<b>%{x}</b><br>Active Personnel: %{y:,}<extra></extra>"
)

fig.update_layout(
    paper_bgcolor="#F7F2E8",
    plot_bgcolor="white",
    title_x=0.5,
    title_font_size=22,
    height=550,
    xaxis_title="Region",
    yaxis_title="Active Personnel",
    coloraxis_showscale=False
)

fig.show()

In [27]:
fig = px.scatter(
    df,
    x="gdp",
    y="defense_budget_usd",
    size="total_assets",
    color="power_index",
    hover_name="country",
    color_continuous_scale="YlOrBr",
    title="💰 Defense Budget vs GDP",
    log_x=True,
    log_y=True
)

fig.update_layout(
    paper_bgcolor="#F7F2E8",
    plot_bgcolor="white",
    title_x=0.5,
    height=600,
    xaxis_title="GDP (Log Scale)",
    yaxis_title="Defense Budget (Log Scale)"
)

fig.show()

In [28]:
fig = px.choropleth(
    df,
    locations="country",
    locationmode="country names",
    color="power_index",
    hover_name="country",
    color_continuous_scale="YlOrBr",
    title="🌍 Global Military Power Index"
)

fig.update_layout(
    paper_bgcolor="#F7F2E8",
    title_x=0.5,
    height=600
)

fig.show()

C:\Users\NAGASH~1\AppData\Local\Temp/ipykernel_27528/3979000987.py:1: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(

In [29]:
top10 = df.sort_values(
    "active_personnel",
    ascending=False
).head(10)

fig = px.bar(
    top10,
    x="country",
    y="active_personnel",
    color="active_personnel",
    text="active_personnel",
    color_continuous_scale="YlOrBr",
    title="👥 Top 10 Countries by Active Personnel"
)

fig.update_traces(
    texttemplate="%{text:.2s}",
    textposition="outside"
)

fig.update_layout(
    paper_bgcolor="#F7F2E8",
    plot_bgcolor="white",
    title_x=0.5,
    height=550,
    coloraxis_showscale=False
)

fig.show()

In [30]:
display(
    df[[
        "country",
        "power_index",
        "gdp",
        "defense_budget_usd",
        "total_assets",
        "active_personnel"
    ]]
    .sort_values("power_index")
    .head(20)
)

,country,power_index,gdp,defense_budget_usd,total_assets,active_personnel
137,United States,0.0741,2.550000e+13,831500000000,432953,1333030
107,Russia,0.0791,9.202187e+10,212638272000,149135,1320000
28,China,0.0919,1.800000e+13,303000000000,169390,2035000
53,India,0.1346,3.390000e+12,109000000000,176033,1431000
117,South Korea,0.1642,9.202187e+10,44800000000,130151,450000
43,France,0.1798,2.780000e+12,67232395000,112434,264000
61,Japan,0.1876,4.230000e+12,58000000000,57483,251500
136,United Kingdom,0.1881,3.070000e+12,88526529585,95276,141330
131,Turkiye,0.1975,9.202187e+10,51400000000,103687,481000
59,Italy,0.2211,2.010000e+12,37325165000,88759,165500
19,Brazil,0.2374,1.920000e+12,26400000000,23965,376000
46,Germany,0.2463,4.070000e+12,127400090000,88466,184324
54,Indonesia,0.2582,1.320000e+12,11155297716,29809,404500
97,Pakistan,0.2626,3.770000e+11,9102115350,67181,660000
58,Israel,0.2707,5.220000e+11,34600000000,65081,169500
55,Iran,0.3199,9.202187e+10,9230000000,83051,610000
6,Australia,0.3208,1.680000e+12,57350000000,17613,58910
119,Spain,0.3247,1.400000e+12,39000676350,50521,121802
37,Egypt,0.3651,9.202187e+10,5193500000,62217,438500
134,Ukraine,0.3691,1.610000e+11,45000000000,48690,900000