In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time

In [2]:
# Read countries list
df = pd.read_csv("data/countries.csv")

print("Total Countries:", len(df))
df.head()

Total Countries: 145

,Rank,Country,Power_Index,Detail_URL
0,1,United States,PwrIndx: 0.0741,https://www.globalfirepower.com/country-milita...
1,2,Russia,PwrIndx: 0.0791,https://www.globalfirepower.com/country-milita...
2,3,China,PwrIndx: 0.0919,https://www.globalfirepower.com/country-milita...
3,4,India,PwrIndx: 0.1346,https://www.globalfirepower.com/country-milita...
4,5,South Korea,PwrIndx: 0.1642,https://www.globalfirepower.com/country-milita...

In [5]:
def scrape_country_details(url):
    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    response = requests.get(url, headers=headers)

    soup = BeautifulSoup(response.text, "html.parser")

    data = {}

    # Country Name
    try:
        data["Country"] = soup.find("h1").text.strip()
    except:
        data["Country"] = ""

    # Power Index
    try:
        power = soup.find("div", class_="contentboxheader")
        data["Power_Index"] = power.text.strip()
    except:
        data["Power_Index"] = ""

    # Store all specifications
    boxes = soup.find_all("div", class_="contentbox")

    for box in boxes:

        title = box.find("span")

        value = box.find("div", class_="textLarge")

        if title and value:

            key = title.text.strip()

            val = value.text.strip()

            data[key] = val

    return data

In [4]:
all_data = []

for index, row in df.iterrows():

    print(f"{index+1}. {row['Country']}")

    details = scrape_country_details(row["Detail_URL"])

    details["Rank"] = row["Rank"]

    details["Country"] = row["Country"]

    details["Power_Index"] = row["Power_Index"]

    all_data.append(details)

    time.sleep(1)

1. United States
2. Russia
3. China
4. India
5. South Korea
6. France
7. Japan
8. United Kingdom
9. Turkiye
10. Italy
11. Brazil
12. Germany
13. Indonesia
14. Pakistan
15. Israel
16. Iran
17. Australia
18. Spain
19. Egypt
20. Ukraine
21. Poland
22. Taiwan
23. Vietnam
24. Thailand
25. Saudi Arabia
26. Sweden
27. Algeria
28. Canada
29. Singapore
30. Greece
31. North Korea
32. Argentina
33. Nigeria
34. Netherlands
35. Myanmar
36. Mexico
37. Bangladesh
38. Portugal
39. Norway
40. South Africa
41. Philippines
42. Malaysia
43. Colombia
44. Iraq
45. Denmark
46. Switzerland
47. Ethiopia
48. Finland
49. Chile
50. Peru
51. Venezuela
52. Romania
53. Uzbekistan
54. United Arab Emirates
55. Czechia
56. Morocco
57. Hungary
58. Kazakhstan
59. Angola
60. Azerbaijan
61. Belgium
62. Bulgaria
63. Serbia
64. Democratic Republic of the Congo
65. Cuba
66. Sudan
67. Austria
68. Sri Lanka
69. Slovakia
70. Belarus
71. Qatar
72. Ecuador
73. Croatia
74. Jordan
75. Bahrain
76. Kuwait
77. Albania
78. Turkmenistan
79. Tunisia
80. Libya
81. Paraguay
82. Bolivia
83. Cambodia
84. Kenya
85. Chad
86. Oman
87. Syria
88. Lithuania
89. Tanzania
90. New Zealand
91. Slovenia
92. Mozambique
93. Mongolia
94. Ireland
95. Georgia
96. Guatemala
97. Uruguay
98. Yemen
99. Cameroon
100. Tajikistan
101. Armenia
102. Latvia
103. Honduras
104. Mali
105. Zimbabwe
106. Estonia
107. Uganda
108. Ivory Coast
109. Kyrgyzstan
110. Luxembourg
111. Zambia
112. Ghana
113. South Sudan
114. North Macedonia
115. Dominican Republic
116. Nicaragua
117. Republic of the Congo
118. Lebanon
119. Eritrea
120. Niger
121. Afghanistan
122. Namibia
123. Mauritania
124. Nepal
125. Laos
126. Senegal
127. Burkina Faso
128. Montenegro
129. El Salvador
130. Botswana
131. Madagascar
132. Gabon
133. Bosnia and Herzegovina
134. Iceland
135. Panama
136. Moldova
137. Somalia
138. Benin
139. Kosovo
140. Sierra Leone
141. Liberia
142. Suriname
143. Central African Republic
144. Beliz
145. Bhutan

In [6]:
details_df = pd.DataFrame(all_data)

details_df.head()

         Country      Power_Index  Rank
0  United States  PwrIndx: 0.0741     1
1         Russia  PwrIndx: 0.0791     2
2          China  PwrIndx: 0.0919     3
3          India  PwrIndx: 0.1346     4
4    South Korea  PwrIndx: 0.1642     5

In [7]:
print(details_df.columns)

Index(['Country', 'Power_Index', 'Rank'], dtype='object')

In [8]:
details_df.to_csv("data/country_details.csv", index=False)

print("country_details.csv saved successfully")

country_details.csv saved successfully

In [9]:
details_df.head(10)

          Country      Power_Index  Rank
0   United States  PwrIndx: 0.0741     1
1          Russia  PwrIndx: 0.0791     2
2           China  PwrIndx: 0.0919     3
3           India  PwrIndx: 0.1346     4
4     South Korea  PwrIndx: 0.1642     5
5          France  PwrIndx: 0.1798     6
6           Japan  PwrIndx: 0.1876     7
7  United Kingdom  PwrIndx: 0.1881     8
8         Turkiye  PwrIndx: 0.1975     9
9           Italy  PwrIndx: 0.2211    10