In [2]:
import pandas as pd
import numpy as np
import re

In [4]:
# Load merged dataset
df = pd.read_csv("merged_military_dataset.csv")

print("Dataset Loaded Successfully!")
print("Original Shape:", df.shape)

df.head()

Dataset Loaded Successfully!
Original Shape: (7881, 73)

,Metric,Rank,Country,Value,Source_URL,power_index_rank,power_index_score,region,continent,alliance,...,border_coverage_km,waterway_coverage_km,assets_per_capita,budget_to_gdp_ratio,military_personnel_per_capita,force_readiness_index,naval_to_land_ratio,air_superiority_index,logistics_index,power_index_rank_gap
0,2026 Military Strength Ranking,1,united states,NaN,https://www.globalfirepower.com/countries-list...,1,0.0741,North America,North America,NATO,...,12002,41009,0.000053,3.238433,0.003898,0.006236,0.099657,0.137431,0.001707,NaN
1,2026 Military Strength Ranking,2,russia,NaN,https://www.globalfirepower.com/countries-list...,2,0.0791,Eastern Europe,Europe,CSTO,...,22407,102000,0.000075,3.492171,0.009374,0.023576,0.132682,0.203210,0.000057,NaN
2,2026 Military Strength Ranking,3,china,NaN,https://www.globalfirepower.com/countries-list...,3,0.0919,East Asia,Asia,Non-Aligned,...,22457,27700,0.000007,0.901839,0.001438,0.001799,0.143271,0.408898,0.000064,NaN
3,2026 Military Strength Ranking,4,india,NaN,https://www.globalfirepower.com/countries-list...,4,0.1346,South Asia,Asia,Non-Aligned,...,13888,14500,0.000005,0.765234,0.001016,0.001725,0.087657,0.218049,0.000113,NaN
4,2026 Military Strength Ranking,5,south korea,NaN,https://www.globalfirepower.com/countries-list...,5,0.1642,East Asia,Asia,Non-Aligned,...,237,1600,0.000069,1.718450,0.008640,0.068162,0.117422,0.157143,0.001073,NaN

In [5]:
# Standardize column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("-", "_", regex=False)
    .str.replace("/", "_", regex=False)
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)

print("Column names standardized successfully.")

df.head()

Column names standardized successfully.

,metric,rank,country,value,source_url,power_index_rank,power_index_score,region,continent,alliance,...,border_coverage_km,waterway_coverage_km,assets_per_capita,budget_to_gdp_ratio,military_personnel_per_capita,force_readiness_index,naval_to_land_ratio,air_superiority_index,logistics_index,power_index_rank_gap
0,2026 Military Strength Ranking,1,united states,NaN,https://www.globalfirepower.com/countries-list...,1,0.0741,North America,North America,NATO,...,12002,41009,0.000053,3.238433,0.003898,0.006236,0.099657,0.137431,0.001707,NaN
1,2026 Military Strength Ranking,2,russia,NaN,https://www.globalfirepower.com/countries-list...,2,0.0791,Eastern Europe,Europe,CSTO,...,22407,102000,0.000075,3.492171,0.009374,0.023576,0.132682,0.203210,0.000057,NaN
2,2026 Military Strength Ranking,3,china,NaN,https://www.globalfirepower.com/countries-list...,3,0.0919,East Asia,Asia,Non-Aligned,...,22457,27700,0.000007,0.901839,0.001438,0.001799,0.143271,0.408898,0.000064,NaN
3,2026 Military Strength Ranking,4,india,NaN,https://www.globalfirepower.com/countries-list...,4,0.1346,South Asia,Asia,Non-Aligned,...,13888,14500,0.000005,0.765234,0.001016,0.001725,0.087657,0.218049,0.000113,NaN
4,2026 Military Strength Ranking,5,south korea,NaN,https://www.globalfirepower.com/countries-list...,5,0.1642,East Asia,Asia,Non-Aligned,...,237,1600,0.000069,1.718450,0.008640,0.068162,0.117422,0.157143,0.001073,NaN

In [6]:
# Remove extra spaces from text columns

text_columns = df.select_dtypes(include=["object"]).columns

for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

print("Extra spaces removed.")

Extra spaces removed.

In [7]:
# Function to clean numeric values

def clean_numeric(value):

    if pd.isna(value):
        return np.nan

    value = str(value)

    # Remove commas
    value = value.replace(",", "")

    # Remove percentage sign
    value = value.replace("%", "")

    # Remove plus sign
    value = value.replace("+", "")

    # Remove dollar symbol
    value = value.replace("$", "")

    # Remove brackets
    value = value.replace("(", "")
    value = value.replace(")", "")

    # Remove units
    value = re.sub(r"km²|sq km|km|mt|bbl|usd|cum", "", value, flags=re.IGNORECASE)

    # Remove unwanted characters
    value = re.sub(r"[^\d\.\-]", "", value)

    if value == "":
        return np.nan

    return value

# Apply cleaning
for col in text_columns:

    if col not in [
        "country",
        "metric",
        "source_url",
        "region",
        "continent",
        "alliance",
        "major_ports_and_terminals"
    ]:

        df[col] = df[col].apply(clean_numeric)

print("Special symbols removed successfully.")

Special symbols removed successfully.

In [8]:
# Convert columns to numeric

for col in df.columns:

    if col not in [
        "country",
        "metric",
        "source_url",
        "region",
        "continent",
        "alliance",
        "major_ports_and_terminals"
    ]:

        df[col] = pd.to_numeric(df[col], errors="coerce")

print("Numeric conversion completed.")

df.info()

Numeric conversion completed.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7881 entries, 0 to 7880
Data columns (total 73 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   metric                                     7881 non-null   object
 1   rank                                       7881 non-null   int64
 2   country                                    7881 non-null   object
 3   value                                      7736 non-null   float64
 4   source_url                                 7881 non-null   object
 5   power_index_rank                           7881 non-null   int64
 6   power_index_score                          7881 non-null   float64
 7   region                                     7881 non-null   object
 8   continent                                  7881 non-null   object
 9   alliance                                   7881 non-null   object
 10  total_population                           7881 non-null   int64
 11  total_military_manpower                    7881 non-null   int64
 12  fit_for_service                            7881 non-null   int64
 13  population_reaching_military_age_annually  7881 non-null   int64
 14  active_personnel                           7881 non-null   int64
 15  reserve_personnel                          7881 non-null   int64
 16  paramilitary                               7881 non-null   int64
 17  total_military_aircraft                    7881 non-null   int64
 18  fighter_aircraft                           7881 non-null   int64
 19  attack_aircraft                            7881 non-null   int64
 20  transport_aircraft                         7881 non-null   int64
 21  trainer_aircraft                           7881 non-null   int64
 22  special_mission_aircraft                   7881 non-null   int64
 23  tanker_aircraft                            7881 non-null   int64
 24  total_military_helicopters                 7881 non-null   int64
 25  attack_helicopters                         7881 non-null   int64
 26  tanks                                      7881 non-null   int64
 27  armored_fighting_vehicles                  7881 non-null   int64
 28  self_propelled_artillery                   7881 non-null   int64
 29  towed_artillery                            7881 non-null   int64
 30  rocket_projectors                          7881 non-null   int64
 31  total_naval_fleet                          7881 non-null   int64
 32  total_naval_fleet_tonnage_mt               2805 non-null   float64
 33  aircraft_carriers                          7881 non-null   int64
 34  helicopter_carriers                        7881 non-null   int64
 35  submarines                                 7881 non-null   int64
 36  destroyers                                 7881 non-null   int64
 37  frigates                                   7881 non-null   int64
 38  corvettes                                  7881 non-null   int64
 39  coastal_patrol_craft                       7881 non-null   int64
 40  mine_warfare_craft                         7881 non-null   int64
 41  defense_budget_usd                         7881 non-null   int64
 42  gdp_usd                                    7881 non-null   int64
 43  external_debt_usd                          7881 non-null   int64
 44  purchasing_power_parity_usd                7881 non-null   int64
 45  foreign_exchange_and_gold_reserves_usd     7881 non-null   int64
 46  total_serviceable_airports                 7881 non-null   int64
 47  labour_force                               7881 non-null   int64
 48  major_ports_and_terminals                  7881 non-null   int64
 49  total_merchant_marine_fleet                7881 non-null   int64
 50  railway_coverage_km                        7881 non-null   int64
 51  roadway_coverage_km                        7881 non-null   int64
 52  oil_production_bbl                         7881 non-null   int64
 53  oil_consumption_bbl                        7881 non-null   int64
 54  proven_oil_reserves_bbl                    7881 non-null   int64
 55  natural_gas_production_cum                 7881 non-null   float64
 56  natural_gas_consumption_cum                7881 non-null   float64
 57  proven_natural_gas_reserves_cum            7881 non-null   float64
 58  coal_production_cum                        7881 non-null   float64
 59  coal_consumption_mt                        7881 non-null   int64
 60  proven_coal_reserves_cum                   7881 non-null   float64
 61  total_land_area_sq_km                      7881 non-null   int64
 62  coastline_coverage_km                      7881 non-null   int64
 63  border_coverage_km                         7881 non-null   int64
 64  waterway_coverage_km                       7881 non-null   int64
 65  assets_per_capita                          7881 non-null   float64
 66  budget_to_gdp_ratio                        7881 non-null   float64
 67  military_personnel_per_capita              7881 non-null   float64
 68  force_readiness_index                      7881 non-null   float64
 69  naval_to_land_ratio                        5881 non-null   float64
 70  air_superiority_index                      7719 non-null   float64
 71  logistics_index                            7881 non-null   float64
 72  power_index_rank_gap                       0 non-null      float64
dtypes: float64(16), int64(51), object(6)
memory usage: 4.4+ MB

In [9]:
# Fill missing numeric values with median

numeric_columns = df.select_dtypes(include=["number"]).columns

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

# Fill missing categorical values with mode

categorical_columns = df.select_dtypes(include=["object"]).columns

for col in categorical_columns:

    if not df[col].mode().empty:
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna("Unknown")

print("Missing values handled successfully.")

Missing values handled successfully.

In [10]:
# Remove completely empty columns

missing_percentage = (df.isnull().sum() / len(df)) * 100

columns_to_drop = missing_percentage[missing_percentage == 100].index.tolist()

if columns_to_drop:
    print("Dropping Columns:", columns_to_drop)
    df.drop(columns=columns_to_drop, inplace=True)
else:
    print("No columns with 100% missing values found.")

Dropping Columns: ['power_index_rank_gap']

In [11]:
before = len(df)

df.drop_duplicates(inplace=True)

after = len(df)

print("Duplicate Rows Removed:", before - after)

Duplicate Rows Removed: 0

In [12]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Missing Percentage Per Column")

print(missing_percentage)

print("\nMaximum Missing Percentage:")

print(round(missing_percentage.max(), 2), "%")

Missing Percentage Per Column
metric                           0.0
rank                             0.0
country                          0.0
value                            0.0
source_url                       0.0
                                ...
military_personnel_per_capita    0.0
force_readiness_index            0.0
naval_to_land_ratio              0.0
air_superiority_index            0.0
logistics_index                  0.0
Length: 72, dtype: float64

Maximum Missing Percentage:
0.0 %

In [13]:
output_file = "final_military_cleaned.csv"

df.to_csv(output_file, index=False)

print(f"Dataset saved successfully as '{output_file}'")

Dataset saved successfully as 'final_military_cleaned.csv'

In [14]:
print("=" * 60)
print("MILITARY DATA CLEANING COMPLETED")
print("=" * 60)

print("Final Dataset Shape:", df.shape)

print("\nFirst 5 Rows")

display(df.head())

============================================================
MILITARY DATA CLEANING COMPLETED
============================================================
Final Dataset Shape: (7881, 72)

First 5 Rows

,metric,rank,country,value,source_url,power_index_rank,power_index_score,region,continent,alliance,...,coastline_coverage_km,border_coverage_km,waterway_coverage_km,assets_per_capita,budget_to_gdp_ratio,military_personnel_per_capita,force_readiness_index,naval_to_land_ratio,air_superiority_index,logistics_index
0,2026 Military Strength Ranking,1,united states,200.0,https://www.globalfirepower.com/countries-list...,1,0.0741,North America,North America,NATO,...,19924,12002,41009,0.000053,3.238433,0.003898,0.006236,0.099657,0.137431,0.001707
1,2026 Military Strength Ranking,2,russia,200.0,https://www.globalfirepower.com/countries-list...,2,0.0791,Eastern Europe,Europe,CSTO,...,37653,22407,102000,0.000075,3.492171,0.009374,0.023576,0.132682,0.203210,0.000057
2,2026 Military Strength Ranking,3,china,200.0,https://www.globalfirepower.com/countries-list...,3,0.0919,East Asia,Asia,Non-Aligned,...,14500,22457,27700,0.000007,0.901839,0.001438,0.001799,0.143271,0.408898,0.000064
3,2026 Military Strength Ranking,4,india,200.0,https://www.globalfirepower.com/countries-list...,4,0.1346,South Asia,Asia,Non-Aligned,...,7000,13888,14500,0.000005,0.765234,0.001016,0.001725,0.087657,0.218049,0.000113
4,2026 Military Strength Ranking,5,south korea,200.0,https://www.globalfirepower.com/countries-list...,5,0.1642,East Asia,Asia,Non-Aligned,...,2413,237,1600,0.000069,1.718450,0.008640,0.068162,0.117422,0.157143,0.001073